#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "12.1.0.11")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::App1.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int appsBg = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorAccent = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimary = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorPrimaryDark = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int gamesBg = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int ic_launcher_background = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int white = 2130771974;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020002
			public const int appsToGamesBG_transition = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int dr_bgApps = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int dr_bgGames = 2130837508;
			
			// aapt resource value: 0x7F020000
			public const int GooglePlayLogo = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int LoginBG = 2130837505;
			
			// aapt resource value: 0x7F020005
			public const int login_background = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int profilePicture = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int rounded_rectangle = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int btnLogin = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int btnSignup = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int linearLayout1 = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int linearLayout2 = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int login_emailInput = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int login_passwordInput = 2130903045;
			
			// aapt resource value: 0x7F030008
			public const int main_btnApps = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int main_btnGames = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int main_btnProfile = 2130903050;
			
			// aapt resource value: 0x7F030006
			public const int main_MainContainer = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int main_SearchBoxContainer = 2130903047;
			
			// aapt resource value: 0x7F03000B
			public const int main_searchTextInput = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int textView1 = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int textView2 = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int textView3 = 2130903054;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040001
			public const int activity_main = 2130968577;
			
			// aapt resource value: 0x7F040000
			public const int Login = 2130968576;
			
			// aapt resource value: 0x7F040002
			public const int signup = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher_foreground = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher_round = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int action_settings = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_name = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F080000
			public const int xamarin_essentials_fileprovider_file_paths = 2131230720;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
